### PR TITLE
Switch to scaffold, broke up body to composables

### PR DESCRIPTION
**Pull request by Iamkosgei**
https://github.com/Bizyback/rhyme/assets/14147462/640716e1-254b-43dc-82d5-4fbec15657d3

### CODE REVIEW

**Comment by MamboBryan** [comment]
Hi @Iamkosgei can you add a screenshot of how the app looks after your implementation?

**Comment by Iamkosgei** [comment]
Hi, @MamboBryan added a video to the PR description.

**Comment by Iamkosgei** [comment]
Hi, @MamboBryan added a video to the PR description.

**Comment by MamboBryan** [comment]
> Hi, @MamboBryan added a video to the PR description.

Awesome work, so is there a way the first row could come below the appbar partially to showcase the haze effect?

**Comment by Iamkosgei** [comment]
https://github.com/Bizyback/rhyme/blob/b07730b75c53d72719e0138dffa18246ea22fbcc/composeApp/src/commonMain/kotlin/ui/screens/titles/TitlesScreen.kt#L124

You can achieve that by changing `top = 40.dp` to something like `16.dp` but the content behind the app bar by default before scrolling looks like a bug, the haze effect can be seen on scroll. Like the case here https://chrisbanes.github.io/haze/media/desktop-small.mp4 what do you think?

**Comment by MamboBryan** [comment]
> https://github.com/Bizyback/rhyme/blob/b07730b75c53d72719e0138dffa18246ea22fbcc/composeApp/src/commonMain/kotlin/ui/screens/titles/TitlesScreen.kt#L124
> 
> You can achieve that by changing `top = 40.dp` to something like `16.dp` but the content behind the app bar by default before scrolling looks like a bug, the haze effect can be seen on scroll. Like the case here https://chrisbanes.github.io/haze/media/desktop-small.mp4 what do you think?

Okay I agree too... So is everything okay I merge it to main @Iamkosgei ?

**Comment by Iamkosgei** [comment]
@MamboBryan Yes, this is good to go.

**Pull request merged**
